---
title: "Operationalizing the use of ecosystem information in Mid-Atlantic science
  and management decisions"
author: "Sarah Gaichas, Geret DePiper, Brandon Muffley"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Abstract:

Operational is defined as "in use or ready for use." The Mid-Atlantic Fishery Management Council (MAFMC) uses ecosystem information operationally in stock assessments, acceptable biological catch specification, and its Ecosystem Approach to Fishery Management (EAFM) process. Ecosystem information has informed stock assessment model assumptions for multiple Mid-Atlantic stocks, and winter bottom temperature is used as a recruitment covariate in the operational Black Sea Bass assessment. Data quality, model performance, and ecosystem information is used in the Scientific and Statistical Committee's determination of scientific uncertainty in the overfishing limit from all assessments, which is used to specify acceptable biological catch for every assessed stock. The MAFMC developed its EAFM process to integrate ecosystem information into its current management system. The full process has been used to evaluate risk from multiple sources using ecosystem indicators, then to integrate these risks into a management strategy evaluation for Summer Flounder, focused on addressing recreational discards. This process resulted in the operational use of a multispecies recreational demand model to set fishery specifications. After the initial cycle, the risk assessment was evaluated and updated to promote further operational use. Council and Advisory Panel members recommended new elements addressing human dimensions (recreational access equity), cross-sectoral impacts (ecological offshore wind development impacts as well as fishery access and scientific impacts), and transitions from static to time series ecosystem indicators (prey availability, predation pressure, and fishing community vulnerability). Targeted ecosystem research developed new indicators, and collaborative refinement of indicators and risk thresholds with MAFMC continues to bring new components of the risk assessment into operational use. Ecosystem reporting has evolved to directly address management objectives and risks. Collaborative development of risk assessment frameworks considering ecosystem information is happening in multiple US regions, providing a broad set of options for current and future operational use. 


# Short description:

The MAFMC uses ecosystem indicators within its comprehensive EAFM risk assessment to prioritize fisheries and issues needing further evaluation. We review MAFMC's 2024 update to the risk assessment, along with the evolution of regional ecosystem reporting to characterize distribution, timing, and productivity shifts and their drivers. 



# Extended abstract:

Operational is defined as "in use or ready for use." In a fishery management context, operational use of information requires clear articulation of management objectives--what are we trying to achieve and what information is needed to achieve it? Operational use of information also requires that the information be standardized, updated, and reported on a regular basis aligned with management time frames. Finally, feedbacks from the management system are needed to make adjustments to the information to achieve management objectives. This is an iterative process for any information, whether it is used in stock assessment, inseason management, or other parts of the fishery management process.

The Mid Atlantic Fishery Management Council (MAFMC) uses ecosystem information operationally in stock assessments, allowable catch specification, and its Ecosystem Approach to Fishery Management (EAFM) process. Ecosystem information has been used to inform stock assessment model assumptions for multiple stocks in the region, and winter bottom temperature is used as a recruitment covariate in the operational Black sea bass assessment. Data quality, model performance, and ecosystem information is used in the Scientific and Statistical Committee (SSC)'s determination of uncertainty in the overfishing limit (OFL) from all assessments, which is used to specify allowable biological catch (ABC) for every assessed stock. The MAFMC developed its EAFM process with specific objectives to integrate ecosystem information into its current management system. The full process has been used to evaluate risk from multiple sources using ecosystem indicators, and then integrate these risks into a management strategy evaluation for summer flounder, focused on addressing recreational discards. An outcome of this process was the operational use of a multispecies recreational demand model to set specifications. 

After this initial cycle, the risk assessment was evaluated and updated to promote further operational use. Council and Advisory Panel members recommended new elements addressing human dimensions (recreational access equity), new elements addressing cross-sectoral impacts (offshore wind impacts on biology and ecosystem as well as fishery access and scientific sampling), and transitions from static ecosystem indicators to time series indicators (prey availability, predation pressure, and fishing community vulnerability). New ecosystem science was required to support these requests. The process included development of new indicators of prey availability based on spatio-temporal modeling using ecological datasets (stomach contents, zooplankton), and new spatial analyses of habitat, revenue, and surveys relative to wind energy development areas. Development of potential risk criteria is ongoing; thresholds between low, moderate, and high risk that are essential to operational use are developed collaboratively with Council and Advisory Panel members. 

Ecosystem reporting is an essential input for annual updates to the EAFM risk assessment. Reporting has evolved to address management objectives and risks directly. Annual reports now organize human dimensions, ecological, and environmental indicators to evaluate performance relative to management objectives. In 2024, the list of climate and ecosystem indicators were re-organized to focus on management risks, including risks to spatial management (distribution shift indicators), risks to seasonal management (timing shift indicators), and risks to quota setting and rebuilding (ecosystem productivity indicators). Indicators in these sections are now poised to further inform the EAFM risk assessment.

There are many operational uses of ecosystem information in the MAFMC management process. Further development of climate and ecosystem informed assessment is ongoing, as well as refinement of the ABC setting process. Collaborative development of risk assessment frameworks considering ecosystem information is happening in multiple US regions, providing a broad set of options for current and future operational use. 


# Talk outline:

Main points

"Operational" means in use or ready for use

"Operationalizing" is an iterative process, especially the using part

Components of an operational process:

*  Clear articulation of management objectives (use)

*  Standardized information updates and reporting (we spend a lot of time on this, understand that operational processes require a lot of time and resources and are *not* research)

*  Feedbacks from the management system and adjustments to achieve management objectives

Mid Atlantic operational use of ecosystem information

*  Stock assessments (ESPs-->assessment structure; ecosystem covariates-->OFL projections)

*  ABC setting (data quality, model performance, and ecosystem information-->OFL CV-->ABC)

*  EAFM risk assessment (ecosystem information-->prioritize scoping and MSE)

In development, research coordinated with SSC

*  Ecosystem overfishing thresholds

Focus on the risk assessment and its operational use, process to bring new science in

Where to even start with ecosystem information can be daunting

*  MAFMC developed an EAFM process with specific objectives to integrate ecosystem information into its current management system

*  Risk assessment first step in process; used to prioritize fishery for further investigation (summer flounder, multiple questions, rec discards, MSE, operational rec demand model resulted)

*  Risk elements link directly to fishery management objectives

*  Risk assessment mainly based on ecosystem indicators in annual reports and management indicators, updated annually by NEFSC and MAFMC staff

*  Feedback from management system and adjustments to achieve management objectives--2022-2023 Council update

How has it changed?

*  New elements addressing human dimensions --> recreational access equity

*  New elements addressing cross-sectoral impacts --> offshore wind impacts on biology and ecosystem as well as fishery access and scientific sampling

*  Static risk indicators --> dynamic, e.g., interest in prey availability, predation pressure, fishing community climate vulnerability

Ecosystem science required for this update

*  Evaluation of potential risk indicators

*  Development of new indicators of prey using spatio temporal modeling based on novel datasets (stomach contents, zooplankton surveys)

*  Spatial analyses of habitat, revenue, surveys relative to wind energy development areas

*  Evaluation of potential risk criteria

How is ecosystem reporting evolving for operational use addressing management risks?

*  Formerly reported a list of climate and ecosystem indicators

*  New focus on management risks --> spatial management (distribution shifts), seasonal management (timing shifts), quota setting and rebuilding (productivity shifts)

*  Further integration with MAFMC risk assessment 

*  Sometimes all it takes is rethinking the visualization (bottom temp)


Conclusions

*  Risk assessment frameworks useful basis for operational use of ecosystem information

*  Multiple ways to *use* this information

*  Collaborative iteration recommended into the future

Alaska has risk tables in assessment, New England developing indicator-based risk policy, likely other examples





