---
title: "Mid-Atlantic Risk Assessment <br /> New information from the <br />State of the Ecosystem"
subtitle: "MAFMC Ecosystem and Ocean Planning Committee and AP Meeting<br /> 27 April 2023"
author: "Sarah Gaichas and Geret DePiper, NOAA Northeast Fisheries Science Center <br /> Brandon Muffley, Mid-Atlantic Fishery Management Council"
output:
  xaringan::moon_reader:
    css: ["default", "libs/EDAB_theme3_508_SOE_16by9.css"]
    lib_dir: libs
    nature:
      titleSlideClass: ["right", "middle", "my-title"]
      ratio: "16:9"
      highlightStyle: githubp
      highlightLines: true
      countIncrementalSlides: false
      beforeInit: "libs/macros.js"
  revealjs::revealjs_presentation:
    self_contained: false
    reveal_plugins: ["notes", "search"]

---
class: top, left

<style>
p.caption {
  font-size: 0.6em;
}
</style>

<style>
.reduced_opacity {
  opacity: 0.5;
}
</style>

```{r setup, include=FALSE}

options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = F,
                      fig.retina = 3,
                      #fig.width = 4,
                      #fig.height = 2,
                      fig.asp = 0.45,
                      warning = F,
                      message = F)

#Plotting and data libraries
library(tidyverse)
library(tidyr)
library(here)
library(kableExtra)
library(ecodata)
library(readxl); library(data.table)
library(DT)
library(widgetframe)

```

```{r, load_refs, include=FALSE, cache=FALSE}
library(RefManageR)
BibOptions(check.entries = FALSE,
           bib.style = "authoryear",
           cite.style = "authoryear",
           longnamesfirst = FALSE,
           max.names = 1,
           style = "markdown")
myBib <- ReadBib("./min.bib", check = FALSE)

#,
#           hyperlink = FALSE,
#           dashed = FALSE

```

```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/human_dimensions_MAB.Rmd-setup.R")}
```

```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/human_dimensions_MAB.Rmd-GIS-setup.R")}
```

```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/macrofauna_MAB.Rmd-setup.R")}
```

```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL_MAB.Rmd-setup.R")}
```

## New information in support of current elements

---
## New information in support of new elements