---
title: "State of the Ecosystem<br /> Mid Atlantic and New England 2025"
subtitle: "East Coast Climate Core Team<br /> 2 April 2025"
author: "Sarah Gaichas and Joseph Caracappa, (editors),<br /> Andy Beet, Brandon Beltz,  Geret DePiper, Kimberly Hyde, Scott Large, Sean Lucey, Laurel Smith (data and section leads), <br />  and all SOE contributors"
output:
  xaringan::moon_reader:
    css: ["default", "libs/EDAB_theme3_508_SOE_16by9.css", "libs/cols.css"]
    lib_dir: libs
    nature:
      titleSlideClass: ["right", "middle", "my-title"]
      ratio: "16:9"
      highlightStyle: githubp
      highlightLines: true
      countIncrementalSlides: false
      beforeInit: ["libs/macros.js", "libs/cols_macro.js"]
  revealjs::revealjs_presentation:
    self_contained: false
    reveal_plugins: ["notes", "search"]
---
class: top, left

<style>
p.caption {
  font-size: 0.6em;
}
</style>

<style>
.reduced_opacity {
  opacity: 0.5;
}
</style>

```{r setup, include=FALSE}

options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = F,
                      fig.retina = 3,
                      #fig.width = 4,
                      #fig.height = 2,
                      fig.asp = 0.45,
                      warning = F,
                      message = F)
#Plotting and data libraries
library(tidyverse)
library(tidyr)
library(here)
library(kableExtra)
library(ecodata)
library(readxl); library(data.table)
library(DT)
library(widgetframe)
library(patchwork)

# if figure output defaults to docs/imaages/ replace with this before moving to 
# presentations/docs in both the html output (search and replace)
# and folder name
# 20220316_MAFMCSSC_Gaichas_files/figure-html/

```
## Risks to Setting Catch Limits: New England

.center[
Indicator: Condition
```{r , fig.alt = "Condition factor for fish species in the MAB based on fall NEFSC bottom trawl survey data. MAB data are missing for 2017 due to survey delays, and no survey was conducted in 2020.", fig.width=20, fig.asp=0.5}
gb <- ecodata::plot_condition(report = "NewEngland", EPU = "GB")
  # theme(axis.text = element_text(size = 12),
  #       plot.title = element_text(size = 12)
  #       )
gom <- ecodata::plot_condition(report = "NewEngland", EPU = "GOM")
    # theme(axis.text = element_text(size = 12),
    #     plot.title = element_text(size = 12)
    #     )

gb + gom + plot_layout(guides = 'collect')  & theme(legend.position = 'bottom',
                                                    legend.text = element_text(size = 10),
                                                    legend.title = element_text(size = 11),
                                                    axis.text.x = element_text(size = 12),
                                                    axis.text.y = element_text(size = 12),
                                                    plot.title = element_text(size = 12))


```

]



